# Generated by Django 4.0.4 on 2022-06-13 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_items_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='actors',
            field=models.TextField(default=0, verbose_name='Актеры'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='items',
            name='description',
            field=models.TextField(default=1, verbose_name='Описание'),
            preserve_default=False,
        ),
    ]
