# Generated by Django 4.0.4 on 2022-06-13 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_items_actors_items_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='ready',
            field=models.BooleanField(default=False),
        ),
    ]
