# Generated by Django 4.0.4 on 2022-06-13 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_docs'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='items',
            options={'verbose_name': 'Мероприятие', 'verbose_name_plural': 'Мероприятия'},
        ),
    ]
