# Generated by Django 4.0.4 on 2022-06-13 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_tasks_alter_task_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='ready',
            field=models.BooleanField(default=False),
        ),
    ]
